version: '3.4'

services:
  db:
    container_name: channel_mysql
    image: mysql:5.7
    command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
    environment:
      TZ: "Asfsia/Seoul"
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_USER: "channel"
      MYSQL_PASSWORD: "pass"
      MYSQL_DATABASE: "channel"
    ports:
    - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppass",  "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3