spring:
  profiles:
    active: dev

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app-detect-language:
    api-key: "Enter the authentication key here"

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/domain?characterEncoding=UTF-8&serverTimezone=UTC&useUnicode=true
    username: domain
    password: pass
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: local

  jpa:
    hibernate:
      ddl-auto: create-drop